### ISSUE TITLE
cannot save new product, however delete and update still can be done

### ISSUE THREAD

**Issue by subtlemalay** [rusty-banks/oShop#1]
![image](https://user-images.githubusercontent.com/57276531/71559527-26a68980-2a9a-11ea-9728-894f994d48ee.png)

I just npm install, ng serve and attached to my own firebase account. Please help. Thanks

**Comment by wittedtweet** [comment]
I'll check this and let you know.

**Comment by wittedtweet** [comment]
Hi,

This error is because we are referring to the 'title' property of the 'product' object in **product-form.component.html** (<input [(ngModel)]="product.**title**" name="title" #title="ngModel" id="title" type="text" class="form-control" required>) which is _undefined_.

To fix this, make the following changes in **product-form-component.ts**:
1) Change **product: Product;** to **product = {};**
2) Optionally remove the import statement of the 'Product' interface in the first line of the file.

Let me know if the issue persists.

**Comment by subtlemalay** [comment]
Thanks for your reply. 

I still have the same issue after removing the Product as interface to   product={}; 
 
![image](https://user-images.githubusercontent.com/57276531/71637408-c83a0080-2c7d-11ea-9a13-7803bfd0cb48.png)

**Comment by wittedtweet** [comment]
Can you post the complete code of your **product-form-component.ts** file here?

**Comment by subtlemalay** [comment]
`import { Product } from './../../models/product';
import { TypeService } from './../../type.service';
import { ProductService } from './../../product.service';
import { CategoryService } from './../../category.service';
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-product-form',
  templateUrl: './product-form.component.html',
  styleUrls: ['./product-form.component.scss']
})
export class ProductFormComponent implements OnInit {
  categories$;
  types$;
  product={};
  id;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private categoryService: CategoryService, 
    private productService: ProductService,
    private typeService: TypeService) {
   
    this.categories$ = categoryService.getAll();
    this.types$ = typeService.getAll();

    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id)
      this.productService.get(this.id)
        .subscribe(p => this.product = p );
  }
  

  save(product) {
    if (this.id)
      this.productService.update(this.id, product);
    else
      this.productService.create(product);

    this.router.navigate(['/admin/products']);
   }

   delete() {
    if (!confirm('Are you sure you want to delete this product?'))
      return;

    this.productService.delete(this.id);
    this.router.navigate(['/admin/products']);
  }

  ngOnInit() {
  }

}`

**Comment by wittedtweet** [comment]
To be frank, I'm not sure where the error is. I also see that you've added a new service- TypeService and I don't know if it is causing issues.

I'd suggest forking my completed code, and comparing it with your own to see where the error is.

**Comment by subtlemalay** [comment]
![image](https://user-images.githubusercontent.com/57276531/71761059-8a4d0e80-2f01-11ea-8bf6-90f8c80b358b.png)

I forked out your code few times. The same error exists. So, I tried one more time. Yup, there error is still there. Below is the code for your reference.

`import { Product } from 'shared/models/product';
import { ProductService } from 'shared/services/product.service';
import { CategoryService } from 'shared/services/category.service';
import { Component } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-product-form',
  templateUrl: './product-form.component.html',
  styleUrls: ['./product-form.component.css']
})
export class ProductFormComponent {
  categories$;
  product: Product;
  id;

  constructor(
    categoryService: CategoryService,
    private productService: ProductService,
    private router: Router,
    private route: ActivatedRoute // to read url params
    ) {
    this.categories$ = categoryService.getAll();

    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id)
      this.productService.get(this.id)
        .subscribe(p => this.product = p);
  }

  save(product) {
    if (this.id)
      this.productService.update(this.id, product);
    else
      this.productService.create(product);

    this.router.navigate(['/admin/products']);
  }

  delete() {
    if (!confirm('Are you sure you want to delete this product?'))
      return;

    this.productService.delete(this.id);
    this.router.navigate(['/admin/products']);
  }
}
`
