### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tonyz0212** [rusty-banks/oShop#2]
Hello, creating a new product does not show in my screen, 
do you know what could be the reason?

**Comment by tonyz0212** [comment]
I am having white screen when trying to run your angular project, could you give me some ideas on how to fix it?

**Comment by tonyz0212** [comment]
i figured it out, 
I forgot to set isAdmin in my firebase project.

**Comment by wittedtweet** [comment]
Glad to hear that you were able to figure out the issue.
